input:
  excel_path: "/home/bdck/PROJECTS_WSL/CREO/650rpm_diag_damp_3D (Dynamic).xlsx"
  x_col: 0            # or "vel_onbalans_Hz"
  usecols: null       # or ["vel_onbalans_Hz", "...ROA (N)", "...ROV (N)"]
    
  # New (simple) toggles:
  order: index        # index | x   (default: index = keep natural row order)
  dropna_x: true      # drop rows where x is NaN

filter:
  # Either absolute rows:
  # start_row: 0
  # end_row: 10000

  # Or fraction window:
  keep_fraction:
    which: window
    start: 0
    end: 0.5

plot:
  engine: plotly
  variables: all      # or list of column names
  combine: grid   # together|separate(several figures)|grid(one figure with subplots)
  title: "650rpm - diag_damp_3D"
  plotly_style: plotly_white
  line_width: 1.5
  line_shape: linear   # linear | spline
  connect_gaps: false  # don’t draw across NaNs

output:
  dir: plots_out
  save: true
  format: html        # (plotly HTML is great for interactivity)
  show: false



