input:
  # Path to Excel (single-sheet)
  excel_path: "/mnt/c/Users/bdck/Documents/CREO/UNICA/AA_manual_copy_for_educational/650rpm_diag_damp_3D (Dynamic).xlsx"

  # X column: integer index, column name, or "all" for chooser in HTML
  x_col: "all"          # e.g. 0 | "vel_onbalans_Hz" | "all"

  # Optional: restrict columns loaded from Excel (speeds up large files)
  usecols: null         # e.g. ["vel_onbalans_Hz", "...ROA (N)", "...ROV (N)"]

filter:
  # Absolute rows:
  # start_row: 0
  # end_row: 10000

  # Fraction window (keeps rows between start and end)
  keep_fraction:
    which: window       # window | first | last | middle
    start: 0.0
    end: 0.5
    # value: 0.3        # for first/last/middle only

plot:
  variables: "all"      # "all" = interactive Y chooser, or list of names for fixed Y
  title: "650rpm - diag_damp_3D"
  plotly_style: plotly_white
  line_width: 1.5
  line_shape: linear     # linear | spline
  connect_gaps: false    # don’t draw across NaNs

output:
  dir: plots_out
  save: true
  format: html           # html | png | pdf | svg (static formats need 'kaleido')
  show: false
